server:
  port: 8081
keycloak:
  auth-server-url: http://localhost:8080
  realm: "spring_keycloak"
  admin-username: admin
  admin-password: admin
  admin-client-id: admin-clid
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/spring_keycloak
